import test from 'node:test';
import assert from 'node:assert/strict';
import {passkeysSupported, passkeyError, signInWithLeaderPasskey, leaderPasskeyAction} from '../src/passkeys.js';
const browser={isSecureContext:true,PublicKeyCredential:function(){},navigator:{credentials:{create(){},get(){}}}};
const session={user:{id:'leader',email_confirmed_at:'2026-01-01'}};
function fixture(role='leader') { const calls=[];let rows=[];return {calls, client:{rpc:async()=>({data:{actor_id:'leader',role}}),auth:{getUser:async()=>({data:{user:session.user}}),signInWithPasskey:async()=>({data:{session}}),registerPasskey:async()=>{calls.push('register');rows=[{id:'key',friendly_name:'Personal'}];return {data:rows[0]};},passkey:{list:async()=>({data:rows}),delete:async({passkeyId})=>{calls.push(passkeyId);rows=[];return {data:{}};}}}}};}
test('requires secure WebAuthn, not platform-only biometric support',()=>{assert.equal(passkeysSupported(browser),true);assert.equal(passkeysSupported({...browser,isSecureContext:false}),false);assert.equal(passkeysSupported({}),false);});
test('passkey sign-in always passes session to existing authority boot',async()=>{const {client}=fixture();let seen;await signInWithLeaderPasskey(client,s=>{seen=s;},browser);assert.equal(seen,session);});
test('cancelled and unsupported sign-ins never boot',async()=>{const {client}=fixture();let boots=0;await assert.rejects(()=>signInWithLeaderPasskey(client,()=>boots++,{}));client.auth.signInWithPasskey=async()=>({error:{name:'NotAllowedError'}});await assert.rejects(()=>signInWithLeaderPasskey(client,()=>boots++,browser));assert.equal(boots,0);assert.match(passkeyError({name:'NotAllowedError'}),/cancelled|timed out/);});
test('enrollment checks current server leader authority and reads back credential',async()=>{const {client,calls}=fixture();const rows=await leaderPasskeyAction(client,'leader','register',null,()=>true,browser);assert.equal(rows[0].id,'key');assert.deepEqual(calls,['register']);});
test('unassigned, wrong actor, stale and anonymous sessions cannot enroll',async()=>{for(const mode of ['participant','wrong','stale','anonymous']){const {client,calls}=fixture(mode==='participant'?'participant':'leader');if(mode==='anonymous')client.auth.getUser=async()=>({data:{user:{...session.user,is_anonymous:true}}});await assert.rejects(()=>leaderPasskeyAction(client,mode==='wrong'?'other':'leader','register',null,()=>mode!=='stale',browser));assert.deepEqual(calls,[]);}});
test('list/delete only current-user credentials and verify deletion',async()=>{const {client,calls}=fixture();await leaderPasskeyAction(client,'leader','register',null,()=>true,browser);await assert.rejects(()=>leaderPasskeyAction(client,'leader','delete','unknown',()=>true,browser));assert.equal((await leaderPasskeyAction(client,'leader','delete','key',()=>true,browser)).length,0);assert.deepEqual(calls,['register','key']);});
test('missing registration readback and failed deletion never report success',async()=>{const {client}=fixture();client.auth.passkey.list=async()=>({data:[]});await assert.rejects(()=>leaderPasskeyAction(client,'leader','register',null,()=>true,browser));client.auth.passkey.list=async()=>({data:[{id:'key'}]});client.auth.passkey.delete=async()=>({data:{}});await assert.rejects(()=>leaderPasskeyAction(client,'leader','delete','key',()=>true,browser));});
test('safe errors preserve password fallback without exposing raw errors',()=>{assert.match(passkeyError({code:'passkey_disabled'}),/password/);assert.match(passkeyError({message:'secret internal details'}),/not completed/);assert.doesNotMatch(passkeyError({message:'secret internal details'}),/secret/);});
