-- Fictional fixtures, disposable database only. Expected RED before 00300.
\set ON_ERROR_STOP on
begin;
do $$
declare a uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); q uuid:=gen_random_uuid();
 s uuid:=gen_random_uuid(); e uuid:=gen_random_uuid(); e2 uuid:=gen_random_uuid(); e3 uuid:=gen_random_uuid();
 c uuid; c2 uuid; rev uuid; req uuid:=gen_random_uuid(); bad uuid:=gen_random_uuid(); r jsonb; saved jsonb; original jsonb; counts jsonb; adj uuid;
begin
 insert into auth.users(id,email) values(a,'attendance-admin@example.invalid');
 insert into rooted.leaders(user_id,display_name,role) values(a,'Attendance admin','admin');
 insert into rooted.participants(id,name,previously_attended) values(p,'Attendance source',true),(q,'Attendance destination',true);
 insert into rooted.seasons(id,name,starts_on,ends_on) values(s,'Attendance test','2026-01-01','2026-12-31');
 insert into rooted.events(id,season_id,name,date,reading_week) values(e,s,'Gate 1','2026-09-28','2026-09-28'),(e2,s,'Gate 2','2026-09-29','2026-09-28'),(e3,s,'Gate 3','2026-09-30','2026-09-28');
 update rooted.rates set attendance=5,bible=2;
 perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 begin
  perform public.rooted_leader_mutate(bad,'checkin',jsonb_build_object('participant_id',p,'event_id',e,'attended',false,'bible',false,'chapters',20));
  raise exception 'FAIL absent creation awarded chapters';
 exception when invalid_parameter_value then null; end;
 begin
  perform public.rooted_leader_mutate(bad,'checkin',jsonb_build_object('participant_id',p,'event_id',e,'attended',false,'bible',true,'chapters',0));
  raise exception 'FAIL absent creation accepted Bible';
 exception when invalid_parameter_value then null; end;
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e,'attended',true,'bible',true,'chapters',20)); c:=(r#>>'{result,receipt,checkin_id}')::uuid;
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e2,'attended',true,'bible',false,'chapters',12)); c2:=(r#>>'{result,receipt,checkin_id}')::uuid;
 execute 'reset role';
 select to_jsonb(x) into original from rooted.checkins x where id=c;
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e,'adjustment',3,'gate-bonus:'||req,'Unrelated bonus',a) returning id into adj;
 counts:=jsonb_build_array((select count(*) from rooted.requests),(select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions));
 execute 'set local role authenticated';
 begin perform public.rooted_correct_checkin(bad,c,null,p,false,false,20); raise exception 'FAIL absent correction accepted chapters'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_correct_checkin(bad,c,null,p,false,true,0); raise exception 'FAIL absent correction accepted Bible'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(bad,adj,c,null,false,false,20); raise exception 'FAIL repair accepted absent chapters'; exception when invalid_parameter_value then null; end;
 execute 'reset role';
 assert counts=jsonb_build_array((select count(*) from rooted.requests),(select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions)),'invalid attempts are atomic';
 update rooted.rates set attendance=19,bible=13;
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(req,c,null,p,false,false,0); saved:=r; rev:=(r#>>'{result,revision_id}')::uuid;
 assert r=public.rooted_correct_checkin(req,c,null,p,false,false,0),'exact retry';
 begin perform public.rooted_correct_checkin(req,c,null,p,false,false,1); raise exception 'FAIL changed retry'; exception when unique_violation then null; end;
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=20,'other attendance 5 + weekly max 12 + manual 3';
 assert (select chapters from rooted.reading_totals where participant_id=p)=12;
 assert (select not attended and not bible and chapters=0 from rooted.effective_checkins where id=c);
 assert (select to_jsonb(x) from rooted.checkins x where id=c)=original;
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,rev,p,true,true,20); rev:=(r#>>'{result,revision_id}')::uuid;
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=35,'historical rates restored, weekly 20 and other attendance/manual preserved';
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,rev,q,false,false,0); rev:=(r#>>'{result,revision_id}')::uuid;
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=20;
 assert (select coalesce(sum(points),0) from rooted.ledger where participant_id=q)=0;
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,rev,q,true,true,8); rev:=(r#>>'{result,revision_id}')::uuid;
 assert public.rooted_correct_checkin(req,c,null,p,false,false,0)=saved,'old receipt replay after transfer';
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=q)=15,'transfer/re-present historical 7 + chapters 8';
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,rev,p,true,true,20); rev:=(r#>>'{result,revision_id}')::uuid;
 r:=public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),adj,c,rev,false,false,0);
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=17,'repair removes selected bonus and own attendance/read contribution only';
 assert (select points from rooted.ledger where id=adj)=3,'manual original immutable';
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c2,null,p,false,false,0);
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=0,'last attended report removal clears weekly credit';
 assert (select chapters from rooted.reading_totals where participant_id=p)=0;
 execute 'set local role authenticated';
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e3,'attended',false,'bible',false,'chapters',0));
 execute 'reset role';
 assert (select sum(points) from rooted.ledger where participant_id=p)=0,'absent creation earns nothing';
 assert not has_function_privilege('anon','public.rooted_correct_checkin(uuid,uuid,uuid,uuid,boolean,boolean,integer)','execute');
 assert not has_function_privilege('service_role','rooted.checkin(jsonb,uuid,uuid)','execute');
 assert (select count(*) from rooted.audit where request_id=req)=1;
 raise notice 'PASS attendance gate: creation/correction/repair fail closed, atomic errors, same-week max, manual preservation, off/on, transfer, historical rates, replay and ACL';
end $$;
set constraints all immediate;
rollback;
