-- Disposable local PostgreSQL only. Always rollback all fictional fixtures.
\set ON_ERROR_STOP on
begin;
do $$
declare
 a uuid:=gen_random_uuid(); admin uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
 p uuid:=gen_random_uuid(); friend uuid:=gen_random_uuid(); s uuid:=gen_random_uuid();
 e1 uuid:=gen_random_uuid(); e2 uuid:=gen_random_uuid(); e3 uuid:=gen_random_uuid();
 c1 uuid; c2 uuid; c3 uuid; req uuid:=gen_random_uuid(); r jsonb; replay jsonb; v jsonb;
 other_before jsonb; original jsonb; n integer; token text:=repeat('a',64);
begin
 insert into auth.users(id,email) values(a,'chapter-leader@example.invalid'),(admin,'chapter-admin@example.invalid'),(outsider,'chapter-unassigned@example.invalid');
 insert into rooted.leaders(user_id,display_name,role) values(a,'Chapter Leader','leader'),(admin,'Chapter Admin','admin');
 insert into rooted.participants(id,name,previously_attended) values(p,'Fictional Chapter Teen',false),(friend,'Fictional Inviter',true);
 insert into rooted.seasons(id,name,starts_on,ends_on) values(s,'Chapter test','2026-01-01','2026-12-31');
 insert into rooted.events(id,season_id,name,date,reading_week) values(e1,s,'Chapter 1','2026-09-28','2026-09-28'),(e2,s,'Chapter 2','2026-09-29','2026-09-28'),(e3,s,'Chapter 3','2026-09-30','2026-09-28');
 perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e1,'attended',true,'bible',true,'chapters',20,'inviter_id',friend));
 c1:=(r#>>'{result,receipt,checkin_id}')::uuid;
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e2,'attended',true,'bible',true,'chapters',12));
 c2:=(r#>>'{result,receipt,checkin_id}')::uuid;
 perform public.rooted_leader_mutate(gen_random_uuid(),'adjustment',jsonb_build_object('participant_id',p,'event_id',e1,'points',-3,'reason','Unrelated manual adjustment'));
 execute 'reset role';
 select jsonb_agg(to_jsonb(l) order by l.id) into other_before from rooted.ledger l where l.kind not in ('reading','reading_correction');
 select to_jsonb(c) into original from rooted.checkins c where c.id=c1;
 insert into rooted.devices(event_id,token_hash,label,issued_by,expires_at) values(e3,extensions.digest(token,'sha256'),'Chapter fixture',a,now()+interval '1 hour');
 execute 'set local role authenticated';
 r:=public.rooted_correct_chapters(req,c1,20,5);
 assert (r#>>'{result,delta_points}')::integer=-8,'20->5 must preserve other report 12';
 assert (r#>>'{result,weekly_after_chapters}')::integer=12;
 replay:=public.rooted_correct_chapters(req,c1,20,5);
 assert replay=r,'Exact retry receipt';
 begin perform public.rooted_correct_chapters(req,c1,20,6); raise exception 'changed retry accepted'; exception when unique_violation then null; end;
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,20,6); raise exception 'stale accepted'; exception when serialization_failure then null; end;
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,5,-1); raise exception 'negative count accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,5,null); raise exception 'null count accepted'; exception when invalid_parameter_value then null; end;
 v:=public.rooted_correct_chapters(gen_random_uuid(),c1,5,8);
 assert (v#>>'{result,delta_points}')::integer=0,'lower report increase must not overcredit';
 v:=public.rooted_correct_chapters(gen_random_uuid(),c2,12,3);
 assert (v#>>'{result,delta_points}')::integer=-4,'lower max becomes 8';
 v:=public.rooted_correct_chapters(gen_random_uuid(),c1,8,10);
 assert (v#>>'{result,delta_points}')::integer=2,'increase after reductions';
 assert public.rooted_correct_chapters(req,c1,20,5)=r,'Old receipt must remain exact after more corrections';
 v:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e1,'attended',true,'bible',true,'chapters',10,'inviter_id',friend));
 assert (v#>>'{result,duplicate}')::boolean,'fresh duplicate accepts effective chapters';
 begin
 perform public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e1,'attended',true,'bible',true,'chapters',20,'inviter_id',friend));
 raise exception 'stale original duplicate accepted'; exception when unique_violation then null; end;
 v:=public.rooted_leader_state('checkins');
 assert exists(select 1 from jsonb_array_elements(v->'rows') x where x->>'id'=c1::text and x->>'chapters'='10' and x->>'original_chapters'='20' and x->>'correction_id' is not null),'effective projection';
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,10,11); raise exception 'unassigned accepted'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,10,11); raise exception 'signed-out accepted'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update rooted.leaders set active=false where user_id=a;
 perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 begin perform public.rooted_correct_chapters(req,c1,20,5); raise exception 'revoked replay accepted'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update rooted.leaders set active=true where user_id=a;
 execute 'set local role service_role';
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,10,11); raise exception 'service accepted'; exception when insufficient_privilege then null; end;
 v:=public.rooted_kiosk(token,'person',jsonb_build_object('participant_id',p));
 assert (v->>'prior_chapters')::integer=10,'kiosk uses corrected maximum';
 v:=public.rooted_kiosk(token,'checkin',jsonb_build_object('participant_id',p,'bible',false,'chapters',11),gen_random_uuid());
 c3:=(v#>>'{result,receipt,checkin_id}')::uuid;
 assert (v#>>'{result,receipt,earned_points}')::integer=6,'future kiosk checkin adds attendance 5 plus chapter 1';
 execute 'reset role';
 select jsonb_agg(to_jsonb(l) order by l.id) into v from rooted.ledger l where l.kind not in ('reading','reading_correction') and l.checkin_id is distinct from c3;
 assert v=other_before,'Attendance, Bible, referral, manual adjustments immutable';
 assert (select to_jsonb(c) from rooted.checkins c where c.id=c1)=original,'Original checkin unchanged';
 assert (select sum(l.points) from rooted.ledger l where l.participant_id=p and l.kind in ('reading','reading_correction'))=11,'chapter net correct';
 assert (select count(*) from rooted.chapter_corrections where checkin_id in (c1,c2))=4,'exact retry no extra history';
 begin update rooted.chapter_corrections set after_chapters=9 where checkin_id=c1; raise exception 'mutable correction'; exception when object_not_in_prerequisite_state then null; end;
 begin update rooted.checkins set chapters=9 where id=c1; raise exception 'mutable checkin'; exception when object_not_in_prerequisite_state then null; end;
 execute 'set local role anon';
 begin perform public.rooted_correct_chapters(gen_random_uuid(),c1,10,11); raise exception 'anonymous accepted'; exception when insufficient_privilege then null; end;
 execute 'set local role authenticated';
 begin perform count(*) from rooted.chapter_corrections; raise exception 'direct read accepted'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update rooted.events set open=false where id=e1;
 perform set_config('request.jwt.claim.sub',admin::text,true);
 execute 'set local role authenticated';
 v:=public.rooted_correct_chapters(gen_random_uuid(),c1,10,0);
 assert (v#>>'{result,delta_points}')::integer=0,'Admin closed-event correction retains third report 11';
 for i in 1..20 loop
   perform public.rooted_correct_chapters(gen_random_uuid(),c1,i-1,i);
 end loop;
 execute 'reset role';
 assert jsonb_array_length(rooted.receipt(c1)->'components')<=4,'Receipt remains bounded after repeated corrections';
 assert (select sum(l.points) from rooted.ledger l where l.participant_id=p and l.kind in ('reading','reading_correction'))=20,'Repeated correction net';
 raise notice 'PASS: leader/admin, denials, exact replay, stale, bounds, reductions/increases, immutable history, other-points preservation, effective projection, kiosk prior and future credit';
end $$;
-- Exercise deferred request/history integrity before removing fixtures.
set constraints all immediate;
rollback;
select count(*)=0 as no_fixture_checkins from rooted.checkins;
