-- Disposable local PostgreSQL, fictional fixtures only.
\set ON_ERROR_STOP on
begin;
do $$
declare a uuid:=gen_random_uuid(); leader uuid:=gen_random_uuid();
 p uuid:=gen_random_uuid(); q uuid:=gen_random_uuid(); s uuid:=gen_random_uuid(); e uuid:=gen_random_uuid(); e2 uuid:=gen_random_uuid();
 c uuid; adj uuid; bonus uuid; negative uuid; badperson uuid; badevent uuid; otherkind uuid; reversal uuid;
 req uuid:=gen_random_uuid(); stale uuid:=gen_random_uuid(); rev uuid; r jsonb; original jsonb; saved jsonb; before_counts jsonb;
begin
 insert into auth.users(id,email) values(a,'repair-admin@example.invalid'),(leader,'repair-leader@example.invalid');
 insert into rooted.leaders(user_id,display_name,role) values(a,'Repair admin','admin'),(leader,'Repair leader','leader');
 insert into rooted.participants(id,name,previously_attended) values(p,'Repair person',true),(q,'Other person',true);
 insert into rooted.seasons(id,name,starts_on,ends_on) values(s,'Repair test','2026-01-01','2026-12-31');
 insert into rooted.events(id,season_id,name,date,reading_week) values(e,s,'Repair event','2026-09-28','2026-09-28'),(e2,s,'Other event','2026-09-29','2026-09-28');
 update rooted.rates set attendance=5,bible=2;
 perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 r:=public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('participant_id',p,'event_id',e,'attended',true,'bible',true,'chapters',20));
 c:=(r#>>'{result,receipt,checkin_id}')::uuid;
 execute 'reset role';
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e,'adjustment',-10,'test-old:'||req,'Explicitly reviewed old workaround',a) returning id into adj;
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e,'adjustment',3,'test-bonus:'||req,'Unrelated bonus with correction keyword',a) returning id into bonus;
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e,'adjustment',2,'test-positive:'||req,'Second reviewed old workaround',a) returning id into negative;
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(q,e,'adjustment',1,'test-person:'||req,'Wrong person',a) returning id into badperson;
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e2,'adjustment',1,'test-event:'||req,'Wrong event',a) returning id into badevent;
 select id into otherkind from rooted.ledger where checkin_id=c and kind='attendance';
 select to_jsonb(x) into original from rooted.checkins x where id=c;
 select to_jsonb(x) into saved from rooted.ledger x where id=adj;
 execute 'set local role authenticated';
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),badperson,c,null,true,true,10); raise exception 'wrong person accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),badevent,c,null,true,true,10); raise exception 'wrong event accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),otherkind,c,null,true,true,10); raise exception 'wrong kind accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),adj,c,null,false,true,10); raise exception 'invalid answer accepted'; exception when invalid_parameter_value then null; end;
 r:=public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10);
 assert r=public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10),'exact retry';
 rev:=(r#>>'{result,revision_id}')::uuid; reversal:=(r#>>'{result,reversal_id}')::uuid;
 assert r->>'action'='checkin.reconcile_adjustment';
 assert (r#>>'{result,reversal_points}')::integer=10;
 assert (r#>>'{result,correction_request_id}')::uuid<>req;
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,11); raise exception 'changed replay accepted'; exception when unique_violation then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),adj,c,rev,true,false,10); raise exception 'second reversal accepted'; exception when unique_violation then null; end;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),reversal,c,rev,true,false,10); raise exception 'reversal selected'; exception when invalid_parameter_value then null; end;
 assert jsonb_array_length(public.rooted_checkin_adjustment_repairs()->'rows')=1;
 begin perform public.rooted_checkin_adjustment_repairs(501,0); raise exception 'invalid pagination'; exception when invalid_parameter_value then null; end;
 execute 'reset role';
 assert (select to_jsonb(x) from rooted.checkins x where id=c)=original;
 assert (select to_jsonb(x) from rooted.ledger x where id=adj)=saved;
 assert (select sum(points) from rooted.ledger where participant_id=p and event_id=e)=20,'27 original -10 manual +3 bonus +2 other manual -12 correction +10 reversal =20';
 assert (select points from rooted.ledger where id=bonus)=3;
 assert (select participant_id=p and attended and not bible and chapters=10 from rooted.effective_checkins where id=c);
 assert (select count(*) from rooted.checkin_adjustment_repairs)=1;
 assert (select count(*) from rooted.audit where request_id=req and action='checkin.reconcile_adjustment' and details#>>'{result,admin_reviewed}'='true')=1;
 before_counts:=jsonb_build_array((select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions),(select count(*) from rooted.requests),(select count(*) from rooted.audit));
 execute 'set local role authenticated';
 begin perform public.rooted_reconcile_checkin_adjustment(stale,negative,c,null,false,false,0); raise exception 'stale accepted'; exception when serialization_failure then null; end;
 execute 'reset role';
 assert before_counts=jsonb_build_array((select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions),(select count(*) from rooted.requests),(select count(*) from rooted.audit)),'stale must roll back all';
 -- Force a failure AFTER the child correction; the child must roll back as well.
 insert into rooted.ledger(participant_id,event_id,kind,points,source,reason,actor_id) values(p,e,'adjustment',1,'checkin.reconcile_adjustment:'||negative,'Injected source collision for atomicity test',a);
 before_counts:=jsonb_build_array((select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions),(select count(*) from rooted.requests),(select count(*) from rooted.audit));
 execute 'set local role authenticated';
 begin perform public.rooted_reconcile_checkin_adjustment(stale,negative,c,rev,false,false,0); raise exception 'source collision accepted'; exception when unique_violation then null; end;
 execute 'reset role';
 assert before_counts=jsonb_build_array((select count(*) from rooted.ledger),(select count(*) from rooted.checkin_revisions),(select count(*) from rooted.requests),(select count(*) from rooted.audit)),'post-correction reversal failure must roll back child';
 assert (select revision_id=rev from rooted.effective_checkins where id=c);
 -- Reverse a positive selected adjustment; unrelated bonus remains unchanged.
 execute 'set local role authenticated';
 r:=public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),bonus,c,rev,true,false,10);
 assert (r#>>'{result,reversal_points}')::integer=-3;
 -- Transfer is a separate ordinary edit. Repair then matches effective, not original, person.
 rev:=(r#>>'{result,revision_id}')::uuid;
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,rev,q,true,false,10);
 rev:=(r#>>'{result,revision_id}')::uuid;
 begin perform public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),negative,c,rev,true,false,9); raise exception 'original person adjustment accepted after transfer'; exception when invalid_parameter_value then null; end;
 r:=public.rooted_reconcile_checkin_adjustment(gen_random_uuid(),badperson,c,rev,true,false,9);
 assert r#>>'{result,participant_id}'=q::text,'repair follows effective person';
 execute 'reset role';
 assert (select participant_id=q and chapters=9 from rooted.effective_checkins where id=c);
 assert (select to_jsonb(x) from rooted.checkins x where id=c)=original;
 execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',leader::text,true);
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10); raise exception 'leader replay'; exception when insufficient_privilege then null; end;
 begin perform public.rooted_checkin_adjustment_repairs(); raise exception 'leader listing'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10); raise exception 'signed out'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update rooted.leaders set active=false where user_id=a;
 perform set_config('request.jwt.claim.sub',a::text,true);
 execute 'set local role authenticated';
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10); raise exception 'revoked replay'; exception when insufficient_privilege then null; end;
 begin perform public.rooted_checkin_adjustment_repairs(); raise exception 'revoked listing'; exception when insufficient_privilege then null; end;
 begin perform count(*) from rooted.checkin_adjustment_repairs; raise exception 'private table'; exception when insufficient_privilege then null; end;
 execute 'set local role anon';
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10); raise exception 'anon'; exception when insufficient_privilege then null; end;
 begin perform public.rooted_checkin_adjustment_repairs(); raise exception 'anon listing'; exception when insufficient_privilege then null; end;
 execute 'set local role service_role';
 begin perform public.rooted_reconcile_checkin_adjustment(req,adj,c,null,true,false,10); raise exception 'service role'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 begin update rooted.checkin_adjustment_repairs set admin_reviewed=false; raise exception 'mutable repairs'; exception when object_not_in_prerequisite_state then null; end;
 begin delete from rooted.checkin_adjustment_repairs; raise exception 'deletable repairs'; exception when object_not_in_prerequisite_state then null; end;
 begin truncate rooted.checkin_adjustment_repairs; raise exception 'truncatable repairs'; exception when object_not_in_prerequisite_state then null; end;
 raise notice 'PASS repair: exact admin replay, both signed reversals, selected-only arithmetic, immutable evidence, wrong person/event/kind, stale and post-child atomic rollback, auth-before-replay and private ACL';
end $$;
set constraints all immediate;
rollback;
