-- Fictional fixtures inherited from behavior.sql, all inside runner rollback.
reset role;
update rooted.leaders set role='admin' where user_id='00000000-0000-4000-8000-000000000001';
set local role anon;
select pg_temp.denied('select public.rooted_station_unlock(''x'',''123456'')','42501','anon unlock ACL');
select pg_temp.denied('select public.rooted_set_checkin_pin(''123456'')','42501','anon PIN ACL');
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',true);
select pg_temp.denied('select public.rooted_set_checkin_pin(''123456'')','42501','unassigned PIN denied');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',true);
select pg_temp.ok(public.rooted_admin_profiles()::text like '%PRIVATE_SENTINEL%','leader contact read');
select pg_temp.ok((public.rooted_set_checkin_pin('012345')->>'ok')::boolean,'leader PIN set');
select pg_temp.denied('select public.rooted_set_checkin_pin(''12345'')','22023','short PIN denied');
select pg_temp.denied('select public.rooted_set_checkin_pin(''abcdef'')','22023','nondigit PIN denied');
select pg_temp.denied('select public.rooted_station_manage(''station.enroll'',''{}'')','42501','leader enrollment denied');
select pg_temp.denied('select public.rooted_station_unlock(''x'',''012345'')','42501','leader direct unlock ACL');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',true);
select pg_temp.denied('select public.rooted_set_checkin_pin(''012345'')','23505','duplicate PIN denied');
select public.rooted_set_checkin_pin('654321');
select pg_temp.denied(format('select public.rooted_station_manage(''station.enroll'',%L::jsonb)',jsonb_build_object('event_id',(select v from test_ctx where k='event2'),'label','Bad TTL','ttl_days',91)),'22023','station TTL capped ninety days');
insert into test_ctx select 'station',public.rooted_station_manage('station.enroll',jsonb_build_object('event_id',v,'label','Fictional Station'))->'station' from test_ctx where k='event2';
select pg_temp.ok(length(v->>'token')=64,'station random256 token') from test_ctx where k='station';
select pg_temp.ok(public.rooted_station_manage('station.list')::text not like '%'||(v->>'token')||'%','station listing no bearer') from test_ctx where k='station';
set local role service_role;
select pg_temp.ok(public.rooted_station_unlock(null,'012345')->>'error'='invalid_station','PIN alone denied');
select pg_temp.ok(public.rooted_station_unlock(repeat('a',64),'012345')->>'error'='invalid_station','unknown station denied');
do $$ declare i integer; r jsonb; begin
 for i in 1..5 loop
  r:=public.rooted_station_unlock((select v->>'token' from test_ctx where k='station'),'111111');
  perform pg_temp.ok(r->>'error'=case when i=5 then 'locked' else 'invalid_pin' end,'wrong PIN attempt '||i);
 end loop;
end $$;
select pg_temp.ok(public.rooted_station_unlock(v->>'token','012345')->>'error'='locked','correct PIN cannot bypass lockout') from test_ctx where k='station';
reset role;
select pg_temp.ok((select failed_attempts=5 and locked_until>clock_timestamp() from rooted.stations where id=(select (v->>'id')::uuid from test_ctx where k='station')),'failure counter persisted between calls');
update rooted.stations set locked_until=clock_timestamp()-interval '1 second';
set local role service_role;
insert into test_ctx select 'unlocked',public.rooted_station_unlock(v->>'token','012345') from test_ctx where k='station';
select pg_temp.ok((v->>'ok')::boolean and length(v->>'device_token')=64 and (v->>'expires_at')::timestamptz<=clock_timestamp()+interval '4 hours','PIN unlock bounded session') from test_ctx where k='unlocked';
select pg_temp.ok(public.rooted_kiosk(v->>'device_token','context')->'event'->'id'=(select v from test_ctx where k='event2'),'station kiosk event scoped') from test_ctx where k='unlocked';
select pg_temp.ok(public.rooted_kiosk(v->>'device_token','search','{"query":"Fictional"}')::text not like '%PRIVATE_SENTINEL%','station kiosk contacts denied') from test_ctx where k='unlocked';
select pg_temp.ok((public.rooted_kiosk(v->>'device_token','checkin',jsonb_build_object('participant_id',(select v from test_ctx where k='other'),'bible',false,'chapters',1),gen_random_uuid())#>>'{result,duplicate}')::boolean,'station checkin existing receipt') from test_ctx where k='unlocked';
reset role;
update rooted.leaders set active=false where user_id='00000000-0000-4000-8000-000000000002';
set local role service_role;
select pg_temp.ok(public.rooted_station_unlock(v->>'token','012345')->>'error'='invalid_pin','inactive leader PIN denied') from test_ctx where k='station';
select pg_temp.denied(format('select public.rooted_kiosk(%L,''context'')',v->>'device_token'),'42501','station inactive issuer denied') from test_ctx where k='unlocked';
reset role;
update rooted.leaders set active=true where user_id='00000000-0000-4000-8000-000000000002';
set local role service_role;
select public.rooted_station_lock(v->>'device_token') from test_ctx where k='unlocked';
select pg_temp.denied(format('select public.rooted_kiosk(%L,''context'')',v->>'device_token'),'42501','locked session denied') from test_ctx where k='unlocked';
update test_ctx set v=public.rooted_station_unlock((select v->>'token' from test_ctx where k='station'),'012345') where k='unlocked';
reset role;
select pg_temp.ok(not exists(select 1 from rooted.audit where action='station.lock' and (actor_id is not null or device_id is null)),'lock audit actual device attribution');
select pg_temp.ok(not exists(select 1 from rooted.requests where payload::text like '%012345%' or response::text like '%012345%') and not exists(select 1 from rooted.audit where details::text like '%012345%'),'PIN absent from receipts audit');
select pg_temp.ok((select pin_hash like '$2%' and pin_hash<>'012345' from rooted.checkin_pins where user_id='00000000-0000-4000-8000-000000000002'),'PIN bcrypt private');
select pg_temp.ok((select failed_attempts=0 and locked_until is null from rooted.stations where id=(select (v->>'id')::uuid from test_ctx where k='station')),'success resets failure count');
update rooted.events set open=false where id=(select (v#>>'{}')::uuid from test_ctx where k='event2');
set local role service_role;
select pg_temp.ok(public.rooted_station_unlock(v->>'token','012345')->>'error'='event_closed','station unlock closed event') from test_ctx where k='station';
select pg_temp.denied(format('select public.rooted_kiosk(%L,''context'')',v->>'device_token'),'22023','station kiosk closed event') from test_ctx where k='unlocked';
reset role;
update rooted.events set open=true where id=(select (v#>>'{}')::uuid from test_ctx where k='event2');
update rooted.stations set created_at=clock_timestamp()-interval '2 days',expires_at=clock_timestamp()-interval '1 day';
set local role service_role;
select pg_temp.ok(public.rooted_station_unlock(v->>'token','012345')->>'error'='invalid_station','expired station unlock denied') from test_ctx where k='station';
select pg_temp.denied(format('select public.rooted_kiosk(%L,''context'')',v->>'device_token'),'42501','expired parent kiosk denied') from test_ctx where k='unlocked';
reset role;
update rooted.stations set expires_at=clock_timestamp()+interval '1 day';
set local role authenticated;
select public.rooted_station_manage('station.revoke',jsonb_build_object('station_id',v->'id')) from test_ctx where k='station';
set local role service_role;
select pg_temp.ok(public.rooted_station_unlock(v->>'token','012345')->>'error'='invalid_station','revoked station unlock denied') from test_ctx where k='station';
select pg_temp.denied(format('select public.rooted_kiosk(%L,''context'')',v->>'device_token'),'42501','revoked parent kiosk denied') from test_ctx where k='unlocked';
reset role;
select pg_temp.ok(not exists(select 1 from rooted.requests r cross join test_ctx t where t.k='station' and (r.payload::text like '%'||(t.v->>'token')||'%' or r.response::text like '%'||(t.v->>'token')||'%')),'station token absent receipts');
select pg_temp.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='rooted' and (has_function_privilege('anon',p.oid,'EXECUTE') or has_function_privilege('authenticated',p.oid,'EXECUTE') or has_function_privilege('service_role',p.oid,'EXECUTE'))),'station helpers private');
select count(*) as passed_assertions,jsonb_agg(label order by label) as passed from test_pass;
