-- Fictional fixtures only. Run on a disposable database after 00400.
\set ON_ERROR_STOP on
begin;
-- Test clock replacement rolls back; production clock has no input or setting.
create or replace function rooted.gathering_now() returns timestamptz language sql volatile set search_path='' as $$ select current_setting('test.weekly_now')::timestamptz $$;
select set_config('test.weekly_now','2026-10-02 20:00:00+00',true);
do $$
declare s uuid:=gen_random_uuid(); e uuid; prev uuid:=gen_random_uuid(); dup uuid:=gen_random_uuid();
 a uuid:=gen_random_uuid(); p uuid:=gen_random_uuid(); q uuid:=gen_random_uuid(); st uuid:=gen_random_uuid();
 secret text:=encode(extensions.gen_random_bytes(32),'hex'); token text; oldtoken text; r jsonb; payload jsonb; saved jsonb; c uuid; pts bigint; req uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email) values(a,'weekly-fiction@example.invalid');
 insert into rooted.leaders(user_id,display_name,role) values(a,'Weekly Fiction','admin');
 insert into rooted.checkin_pins(user_id,pin_hash) values(a,extensions.crypt('012345',extensions.gen_salt('bf',4)));
 insert into rooted.participants(id,name,previously_attended) values(p,'Weekly Fiction A',true),(q,'Weekly Fiction B',true);
 insert into rooted.seasons(id,name,starts_on,ends_on) values(s,'Weekly Fiction','2026-09-25','2026-11-27');
 insert into rooted.weekly_schedule(season_id,enabled) values(s,true);
 insert into rooted.events(id,season_id,name,date,reading_week,open) values(prev,s,'Past','2026-09-25','2026-09-21',true);
 perform rooted.weekly_maintain();
 assert (select array_agg(date order by date)=array['2026-09-25','2026-10-02','2026-10-09','2026-10-16','2026-10-23','2026-11-06','2026-11-13','2026-11-20']::date[] from rooted.events where season_id=s),'four/five-Friday months exclude last Friday, retain historical Sep25 and third Fridays';
 assert not (select open from rooted.events where id=prev),'past auto closes';
 assert (select bool_and(extract(isodow from date)=5 and reading_week=date_trunc('week',date)::date) from rooted.events where season_id=s);
 select id into e from rooted.events where season_id=s and date='2026-10-02';
 update rooted.events set open=false where season_id=s and date='2026-10-16';
 perform rooted.weekly_maintain();
 assert (select count(*)=8 from rooted.events where season_id=s),'idempotency';
 assert not (select open from rooted.events where season_id=s and date='2026-10-16'),'manual closure preserved';
 insert into rooted.stations(id,event_id,label,token_hash,authorized_by,expires_at) values(st,prev,'Weekly Fiction',extensions.digest(secret,'sha256'),a,'2026-12-01');
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'999999'); assert r->>'error'='invalid_pin';
 execute 'reset role';
 assert (select event_id=prev from rooted.stations where id=st),'bad PIN never rolls station';
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); token:=r->>'device_token';
 assert r->>'event_id'=e::text and r->>'ok'='true','valid PIN rolls same-season station to today';
 assert (r->>'expires_at')::timestamptz='2026-10-03 04:00+00'::timestamptz;
 payload:=jsonb_build_object('event_id',e,'participant_id',p,'bible',true,'chapters',3);
 r:=public.rooted_kiosk(token,'checkin',payload,req); saved:=r; c:=(r#>>'{result,receipt,checkin_id}')::uuid;
 assert c is not null;
 assert public.rooted_kiosk(token,'checkin',payload,req)=saved,'exact retry';
 begin perform public.rooted_kiosk(token,'checkin',payload||jsonb_build_object('event_id',prev),gen_random_uuid()); raise exception 'FAIL stale event accepted'; exception when insufficient_privilege then null; end;
 begin perform public.rooted_kiosk(token,'checkin',payload-'event_id',gen_random_uuid()); raise exception 'FAIL missing event accepted'; exception when invalid_parameter_value then null; end;
 execute 'reset role';
 select sum(points) into pts from rooted.ledger where participant_id=p;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform set_config('test.weekly_now','2026-10-03 04:00:00+00',true);
 -- Denied exactly at midnight even before the maintenance job physically closes.
 execute 'set local role service_role';
 begin perform public.rooted_kiosk(token,'context'); raise exception 'FAIL stale token'; exception when insufficient_privilege then null; end;
 execute 'set local role authenticated';
 begin perform public.rooted_leader_mutate(gen_random_uuid(),'checkin',jsonb_build_object('event_id',e,'participant_id',q,'attended',true,'bible',false,'chapters',0)); raise exception 'FAIL late leader checkin'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 perform rooted.weekly_maintain();
 assert not (select open from rooted.events where id=e);
 assert (select sum(points)=pts from rooted.ledger where participant_id=p),'closure preserves points';
 execute 'set local role authenticated';
 r:=public.rooted_correct_checkin(gen_random_uuid(),c,null,p,true,false,4);
 assert r->>'action'='checkin.correct','saved leader correction allowed after closure';
 execute 'reset role';
 oldtoken:=token;
 perform set_config('test.weekly_now','2026-10-09 20:00+00',true);
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); token:=r->>'device_token'; assert r->>'ok'='true';
 begin perform public.rooted_kiosk(oldtoken,'context'); raise exception 'FAIL old device resurrected'; exception when insufficient_privilege then null; end;
 begin perform public.rooted_kiosk(token,'checkin',payload,req); raise exception 'FAIL queued intent reattributed'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 -- Ambiguous today never chooses newest or arbitrary event.
 update rooted.stations set event_id=prev where id=st;
 insert into rooted.events(id,season_id,name,date,reading_week) values(dup,s,'Ambiguous','2026-10-09','2026-10-05');
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); assert r->>'error'='ambiguous_current_gathering';
 execute 'reset role';
 update rooted.events set open=false where id=dup;
 perform set_config('test.weekly_now','2026-10-10 20:00+00',true);
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); assert r->>'error'='no_current_gathering';
 execute 'reset role';
 -- Skipped last Friday must not roll a paired station or issue daily authority.
 perform set_config('test.weekly_now','2026-10-30 20:00+00',true);
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); assert r->>'error'='no_current_gathering';
 execute 'reset role';
 assert (select event_id=prev from rooted.stations where id=st),'skipped Friday never reassigns station';
 -- Even a manually added last-Friday row cannot bypass the private schedule.
 insert into rooted.events(season_id,name,date,reading_week) values(s,'Excluded manual','2026-10-30','2026-10-26') returning id into dup;
 assert not rooted.meeting_today(dup,'2026-10-30 20:00+00');
 update rooted.stations set event_id=dup where id=st;
 execute 'set local role service_role';
 r:=public.rooted_station_unlock(secret,'012345'); assert r->>'error'='event_closed';
 execute 'reset role';
 assert not rooted.weekly_date_eligible(s,'2026-09-18'),'before season';
 assert not rooted.weekly_date_eligible(s,'2026-12-04'),'after season';
 assert not rooted.weekly_date_eligible(s,'2026-11-27'),'last-Friday season endpoint';
 assert rooted.weekly_date_eligible(s,'2026-11-20'),'third Friday remains';
 insert into rooted.weekly_exceptions values(s,'2026-11-20','Fictional explicit exception');
 assert not rooted.weekly_date_eligible(s,'2026-11-20'),'private exceptions also enforced';
 assert rooted.meeting_today(e,'2026-10-03 03:59:59+00');
 assert not rooted.meeting_today(e,'2026-10-03 04:00+00');
 assert (('2026-03-08 05:00+00'::timestamptz at time zone 'America/New_York')::date+1)::timestamp at time zone 'America/New_York'='2026-03-09 04:00+00'::timestamptz;
 assert (('2026-11-01 04:00+00'::timestamptz at time zone 'America/New_York')::date+1)::timestamp at time zone 'America/New_York'='2026-11-02 05:00+00'::timestamptz;
 assert not has_function_privilege('anon','rooted.weekly_maintain()','execute');
 assert not has_function_privilege('authenticated','rooted.weekly_maintain_at(timestamptz)','execute');
 assert not has_function_privilege('service_role','rooted.gathering_now()','execute');
 assert not has_function_privilege('service_role','rooted.kiosk_before_weekly(text,text,jsonb,uuid)','execute');
 assert not has_table_privilege('authenticated','rooted.weekly_schedule','insert');
 assert not has_function_privilege('authenticated','rooted.weekly_date_eligible(uuid,date)','execute');
 raise notice 'PASS weekly: bounded recurrence excluding last Fridays, historical preservation, idempotency, manual closure, midnight/DST, preserved points, closed correction, valid-PIN rollover, stale/missing event denial, ambiguity/no-current, private ACLs';
end $$;
do $$ declare s uuid:=gen_random_uuid(); e uuid; r jsonb; begin
 insert into rooted.seasons(id,name,starts_on,ends_on) values(s,'Spring boundary fiction','2027-03-05','2027-04-02');
 insert into rooted.weekly_schedule(season_id,enabled) values(s,true);
 r:=rooted.weekly_maintain_at('2027-03-05 05:00+00');
 assert (select array_agg(date order by date)=array['2027-03-05','2027-03-12','2027-03-19','2027-04-02']::date[] from rooted.events where season_id=s),'inclusive season endpoints, skip March last Friday, spring DST';
 select id into e from rooted.events where season_id=s and date='2027-03-12';
 assert rooted.meeting_today(e,'2027-03-13 04:59:59+00') and not rooted.meeting_today(e,'2027-03-13 05:00+00'),'pre-DST midnight';
 select id into e from rooted.events where season_id=s and date='2027-03-19';
 assert rooted.meeting_today(e,'2027-03-20 03:59:59+00') and not rooted.meeting_today(e,'2027-03-20 04:00+00'),'post-DST midnight';
 r:=rooted.weekly_maintain_at('2027-04-03 04:00+00');
 assert (select count(*)=4 and bool_and(not open) from rooted.events where season_id=s),'after season closes without generating outside season';
 raise notice 'PASS spring DST and inclusive season endpoints';
end $$;
rollback;
